nome : testes

em :
  pull_request :
    tipos : [aberto, sincronizado, reaberto]
  empurre :
    ramos :
      - principal

empregos :
  testes :
    roda em : ubuntu-mais recente
    passos :
      - nome : Repositório de check-out
        usa : ações / checkout @ v2

      - name : Setup Node.js
        usa : actions / setup-node @ v1
        com :
          versão do nó : " 12.x "

      - nome : Preparar cache
        usa : ações / cache @ v2
        com :
          caminho : ~ / .npm
          chave : $ {{runner.os}} - node - $ {{hashFiles ('** / package-lock.json')}}
          chaves de restauração : |
            $ {{runner.os}} - nó-
      - nome : instale dependências
        correr : npm ci

      - nome : Executar testes
        executar : npm executar teste: ci

      - nome : Macacão
        usa : coverallsapp / github-action @ master
        com :
          github-token : $ {{secrets.GITHUB_TOKEN}}